include:
  - project: 'dependabot-gitlab/dependabot-standalone'
    file: '.gitlab-ci.yml'

image: node:latest

stages:
  - dependabot
  - deploy

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    #- public/
    - .cache/

pages:
  stage: deploy
  only:
    - main
  script:
    - npm install
    - npm run build
    - mv build public
  artifacts:
    paths:
    - public

.dependabot-gitlab:
  stage: dependabot
